name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

  steps:
  - name: Checkout
    uses: actions/checkout@v4
  
	- name: Configure AWS Credentials
		uses: aws-actions/configure-aws-credentials@v4
		with:
			role-to-assume: 
			aws-region: 